"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['LeaderBoard.py']
DATA_FILES = ['Main.py',
 'SudokuGame.py',
 'SudokuGameGUI.py',
 'SudokuSolver.py',
 'SudokuSolverGUI.py',
 'setup.py']
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
